- name: Add Neovim repository
  become: yes
  tags:
    - install-apps
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
